import streamlit as st
import base64
from io import BytesIO
from docx import Document

from transformers import pipeline
text_gen = pipeline("text-generation", model="gpt2")

"""
Purpose:
Support educators in designing interdisciplinary, social justice-oriented learning productions aligned with academic standards, CASEL-based SEL, civic engagement, and identity development. 
Includes support for professional production environments (e.g., recording studios, photo/video studios, radio stations).
Generates a unit overview, unit plan, and daily lesson plans. Allows for user feedback to iteratively refine or manually edit the generated plans.
"""

CASEL_CORE_COMPETENCIES = [
    "Self-awareness",
    "Self-management",
    "Social awareness",
    "Relationship skills",
    "Responsible decision-making"
]

STATE_STANDARDS_EXAMPLES = {
    "CA": "Aligned with A-G requirements & CA CTE Pathways",
    "NY": "NYS Standards and CDOS",
    "TX": "TEKS + CTE standards",
    "MN": "Minnesota Academic Standards",
    "Common Core": "CCSS-aligned skills and interdisciplinary anchor standards",
    "Other": "Locally defined learning outcomes"
}

ENVIRONMENTS = {
    "Recording Studio": ["Audio engineering software", "Microphones", "Sound boards"],
    "Photo/Video Studio": ["Cameras", "Lighting kits", "Editing software"],
    "Radio Station": ["Broadcast mics", "Digital consoles", "Stream encoders"],
    "Mobile Gear Kit": ["Lavaliers", "Portable recorders", "Tablets"]
}

if "refinements" not in st.session_state:
    st.session_state.refinements = []

if "final_output" not in st.session_state:
    st.session_state.final_output = ""

def create_docx_export(content, title):
    doc = Document()
    # Cover Page
    doc.add_heading("Learning Production Plan", 0)
    doc.add_paragraph(f"Title: {title}")
    doc.add_paragraph("Generated by the Learning Production Designer GPT")
    doc.add_paragraph("\n")
    doc.add_page_break()

    # Main Content
    sections = content.strip().split('\n\n')
    for section in sections:
        if section.strip():
            if ':' in section:
                header, body = section.split(':', 1)
                doc.add_heading(header.strip(), level=1)
                for line in body.strip().split('\n'):
                    doc.add_paragraph(line.strip())
            else:
                doc.add_paragraph(section.strip())

    # Add CASEL and CTE resource links at the end
    doc.add_page_break()
    doc.add_heading("Appendix: Key Framework Resources", level=1)
    doc.add_paragraph("- CASEL Core SEL Competencies: https://casel.org/fundamentals-of-sel/what-is-the-casel-framework")
    doc.add_paragraph("- California CTE Arts, Media, and Entertainment Standards: https://www.cde.ca.gov/ci/ct/gs/amestandards.asp")

    buffer = BytesIO()
    doc.save(buffer)
    buffer.seek(0)
    return buffer

def apply_feedback_to_output(original, feedback_list):
    feedback_summary = "\n".join([f"- {f}" for f in feedback_list])
    prompt = f"Improve the following educational unit plan based on these suggestions:\n{feedback_summary}\n\nORIGINAL PLAN:\n{original}\n\nREVISED PLAN:" 
    generated = text_gen(prompt, max_length=1024, do_sample=True, temperature=0.7)[0]['generated_text']
    return generated.split("REVISED PLAN:")[-1].strip()

def design_learning_production(theme, subject_area, duration_weeks, grade_level, student_identity_focus=None, state_code="Other", environment="Recording Studio"):
    title = f"{theme.title()} Through {subject_area}"
    identity_phrase = f" from the lens of {student_identity_focus}" if student_identity_focus else ""
    driving_question = f"How can {grade_level} students use {subject_area.lower()} to understand and impact the issue of {theme.lower()}{identity_phrase}?"

    tools = ENVIRONMENTS.get(environment, [])

    weekly_breakdown = []
    daily_lessons = []
    for week in range(1, duration_weeks + 1):
        competency = CASEL_CORE_COMPETENCIES[(week - 1) % len(CASEL_CORE_COMPETENCIES)]
        weekly_breakdown.append(f"Week {week}: Focus on {competency}. Students engage in production planning, iteration, and peer critique.")
        for day in range(1, 6):
            daily_lessons.append(f"Week {week}, Day {day}: Hands-on work in {environment}. Emphasize use of: {', '.join(tools)}. Guided reflection on {competency.lower()} and community connection.")

    reflection_prompts = [
        f"Week {i+1}: What did you discover about yourself and your community this week?"
        for i in range(duration_weeks)
    ]

    assessment = {
        "Academic": STATE_STANDARDS_EXAMPLES.get(state_code, STATE_STANDARDS_EXAMPLES["Other"]),
        "SEL": f"Aligned with CASEL: {', '.join(CASEL_CORE_COMPETENCIES)}",
        "Civic Impact": "Real-world presentation, feedback, and social engagement"
    }

    sel_and_civic = {
        "Identity Work": "Cultural storytelling, identity mapping, expressive media",
        "Voice & Agency": "Student-driven content and role selection",
        "Community Engagement": "Authentic partner dialogue and event facilitation"
    }

    resources = {
        "Tech": ", ".join(tools),
        "People": "Facilitators, creatives, collaborators",
        "Materials": "Mixed media, journaling supplies, event tools"
    }

    summary = f"""
UNIT OVERVIEW
TITLE: {title}
DRIVING QUESTION: {driving_question}

WEEKLY PLAN:
{chr(10).join(f'- {week}' for week in weekly_breakdown)}

UNIT PLAN (Daily Lessons):
{chr(10).join(f'- {lesson}' for lesson in daily_lessons)}

ASSESSMENT OVERVIEW:
Academic: {assessment['Academic']}
SEL: {assessment['SEL']}
Civic Impact: {assessment['Civic Impact']}

SEL & CIVIC INTEGRATION:
Identity Work: {sel_and_civic['Identity Work']}
Voice & Agency: {sel_and_civic['Voice & Agency']}
Community Engagement: {sel_and_civic['Community Engagement']}

RESOURCES:
Tech: {resources['Tech']}
People: {resources['People']}
Materials: {resources['Materials']}

STUDENT REFLECTION PROMPTS:
{chr(10).join(f'- {prompt}' for prompt in reflection_prompts)}
"""

    return summary, title

st.title("🎓 Learning Production Designer")

with st.form("learning_production_form"):
    theme = st.text_input("Theme (e.g. Climate Justice)")
    subject_area = st.selectbox("Subject Area", ["Science", "Language Arts", "Humanities"])
    duration_weeks = st.slider("Duration (weeks)", min_value=1, max_value=12, value=4)
    grade_level = st.text_input("Grade Level (e.g. 11th grade)")
    identity = st.text_input("Student Identity Focus (optional)")
    state_code = st.selectbox("Standards Alignment", list(STATE_STANDARDS_EXAMPLES.keys()))
    environment = st.selectbox("Production Environment", list(ENVIRONMENTS.keys()))
    submitted = st.form_submit_button("Generate Plan")

if submitted:
    output, plan_title = design_learning_production(
        theme, subject_area, duration_weeks, grade_level, identity, state_code, environment
    )
    st.session_state.generated_plan = output
    st.session_state.final_output = output
    st.subheader("📄 Generated Learning Production Plan")
    st.markdown(st.session_state.generated_plan)
    st.download_button("📄 Download as TXT", output, file_name="learning_production_plan.txt")
    docx_buffer = create_docx_export(output, plan_title)
    st.download_button("📄 Download as DOCX", data=docx_buffer, file_name="learning_production_plan.docx")

if "generated_plan" in st.session_state:
    st.subheader("✏️ Manual Edit or AI Refinement")
    mode = st.radio("Choose editing method:", ["Manually edit text", "Suggest improvements only"])

    if mode == "Manually edit text":
        st.session_state.final_output = st.text_area("Edit your learning production plan directly below:", value=st.session_state.generated_plan, height=700)
    else:
        user_feedback = st.text_area("What would you like to change or improve? Be specific.")
        if st.button("Submit Refinement"):
            st.session_state.refinements.append(user_feedback)
            new_output = apply_feedback_to_output(st.session_state.generated_plan, st.session_state.refinements)
            st.session_state.final_output = new_output
            st.success("AI refinement applied.")
            st.text_area("Revised Plan:", value=new_output, height=700)
            st.download_button("📥 Download Final Version as TXT", new_output, file_name="customized_learning_production.txt")
